app = "quovi-frontend"
primary_region = "iad"

[build]
  dockerfile = "frontend/Dockerfile"
  ignorefile = "frontend/.dockerignore"
  [build.args]
    NEXT_PUBLIC_API_URL = "https://quovi-backend.fly.dev/api"
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = "268691260379-gq3u019erlkn68103l7fttpsp3jm7hoo.apps.googleusercontent.com"

[env]
  PORT = "3000"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1